version: 2

# Jobs 
base: &base
  docker:
  - image: circleci/php:7.1-node-browsers

tests: &tests
  command: |
    composer install
    composer test

lint: &lint
  command: |
    composer lint
    
setup: &setup
  command: |
    printenv >> ".env"
    
jobs:
  build-and-test:
    <<: *base
    steps:
    - checkout
    - run: *setup
    - run: *tests
    - run: *lint

workflows:
  version: 2
  build:
    jobs:
    - build-and-test:
        filters:
          branches:
            only:
            - master
